module.exports = {
  apps: [
    {
      name: "ctrader-long-live",
      script: "main-async.py",
      interpreter: "python3",
      //   args: "test",
      //   cwd: "/Users/langdon0003/Better-cTrader-OpenAPI-Sample",
      cwd: "/root/Multiprocess-cTrader-OpenAPI-Sample",
      env_file: ".env.long-live",
      error_file: "./logs/long-live-err.log",
      out_file: "./logs/long-live-out.log",
      log_file: "./logs/long-live-combined.log",
      time: true,
      autorestart: true,
      max_memory_restart: "1G",
    },
    {
      name: "ctrader-long-demo",
      script: "main-async.py",
      interpreter: "python3",
      //   args: "test",
      //   cwd: "/Users/langdon0003/Better-cTrader-OpenAPI-Sample",
      cwd: "/root/Multiprocess-cTrader-OpenAPI-Sample",
      env_file: ".env.long-demo",
      error_file: "./logs/long-demo-err.log",
      out_file: "./logs/long-demo-out.log",
      log_file: "./logs/long-demo-combined.log",
      time: true,
      autorestart: true,
      max_memory_restart: "1G",
    },
  ],
};
